#!/bin/bash

TXT_BLD=$(tput bold)
TXT_GREEN=$(tput setaf 2)
TXT_RESET=$(tput sgr0)

if echo "\n" | grep -q 'n'
then e_='-e'
else e_=''
fi

techo() { echo $e_ "$TXT_GREEN$TXT_BLD$1$TXT_RESET"; } # script title

techo "[OPEN PORT] $@"
