#!/usr/bin/env bash
apt-get -y install build-essential git-core python-dev
python oscied_lib/setup.py install  # kombu error
python osiced_lib/setup.py install  # Then it works ...
python oscied_lib/OrchestraHooks.py install
